options:
  vips:
    type: string
    default: ""
    description: "List of virtual IP address to be announced. Comma separated in CIDR format"
  local_as:
    type: int
    default: 0
    description: "Local AS number (Autonomous System Numer)"
  peer_as:
    type: int
    default: 0
    description: "Peer AS number (Autonomous System Numer)"
  router_id:
    type: string
    default: ""
    description: "Router ID"
  hold_time:
    type: int
    default: 0
    description: "Optional hold time. 0 to disable"
  neighbors:
    type: string
    default: ""
    description: "Comma separated list of neighbor IP addresses"
  healthcheck_cmd:
    type: string
    default: "/bin/true"
    description: |
      Service healthcheck command.
      VIP is anncounced as long as check passes